# Generated by Django 5.2.9 on 2025-12-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhabit',
            name='goal',
            field=models.IntegerField(default=1),
        ),
    ]
